# Generated by Django 5.0.6 on 2024-08-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_status_complaint_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_category', models.CharField(max_length=255)),
                ('phone_subcategory', models.CharField(max_length=255)),
                ('phone_model', models.CharField(max_length=255)),
                ('phone_complaint', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('issue_description', models.TextField()),
                ('pickup_address', models.TextField()),
                ('terms_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('on_working', 'On Working'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
