# Generated by Django 5.0.6 on 2024-08-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_servicerequest_phone_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='phone_category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone_complaint',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone_model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone_subcategory',
            field=models.CharField(max_length=255),
        ),
    ]
