# Generated by Django 5.0.6 on 2024-08-31 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_servicerequest_phone_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='phone_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.phonecategory'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone_complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.complaint'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.phonemodel'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.phonesubcategory'),
        ),
    ]
