# Generated by Django 5.0.6 on 2024-09-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('completed', 'Completed')], max_length=20),
        ),
    ]
